# Build todos Api
FROM node:16-alpine AS builder

WORKDIR /app

COPY todos-api/package.json todos-api/package-lock.json ./
RUN npm install

COPY todos-api/ ./

FROM node:16-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/ ./

EXPOSE 8082

CMD ["node", "server.js"]
