# Build users api 
FROM maven:3.8-openjdk-11 AS builder

WORKDIR /app
COPY users-api/pom.xml .
RUN mvn dependency:go-offline


COPY users-api/src ./src
RUN mvn package -DskipTests

FROM eclipse-temurin:8-jre

WORKDIR /app

COPY --from=builder /app/target/*.jar /app/users-api.jar

EXPOSE 8083

ENTRYPOINT ["java", "-jar", "/app/users-api.jar"]
